//! Auto-generated FFI bindings to libarchive
//!
//! This will be generated by bindgen during build

// TODO: Add bindgen-generated bindings here
// For now, placeholder types

#[allow(dead_code)]
pub struct ArchiveHandle;
